baseURL = "https://github.com/firben-sass/compweb"
title = "Music Genre Identification based on Amazon Vinyl Records Reviews"
description = "This is a project description"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Signe Wulff-Andersen", "Danyu Shen"]
    notebook = "/explainer-notebook.html"
    github = "https://github.com/firben-sass/compweb"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"
    [[params.nav]]
        label = "Discussion"
        link = "/discussion"

